### ISSUE TITLE
Please consider node-red-contrib- naming

### ISSUE THREAD

**Issue by knolleary** [TLacke/node-red-multi-sensor#1]
Hi there - thanks for creating a node and sharing it with the community.

One request - as per our [packaging guidelines](http://nodered.org/docs/creating-nodes/packaging), we ask that 3rd party nodes use the `node-red-contrib-` prefix to their name. This ensures they don't get mistaken for nodes maintained by the project itself.

You're under no obligation to change the name, but I hope you'll consider it.

Many thanks, Nick

**Comment by TLacke** [comment]
Hi, i tried to change the name, but as I'm pretty new to publish npm and
nodered i got to read a lot but didn't find a way to change the name.

As i understood it isn't possible to do it.
But you have a solution?

Or do I only change the name in the package.json?

Cheers
  /Tommy

**Comment by TLacke** [comment]
Renamed to node-red-contrib-multi-sensor
