### ISSUE TITLE
Reset trigger

### ISSUE THREAD

**Issue by Zaitsev** [TLacke/node-red-multi-sensor#2]
How to reset trigger?

**Comment by TLacke** [comment]
There are no current feature for resetting the node.
If there's interest in having this feature, I'll add a feature for it.

**Comment by TLacke** [comment]
I've reworked the source and enabled both timeout's on sensor level and active state.
Also added a custom message 'reset' function _(msg.reset='soft|hard')_ to enable flow reset control.

**Comment by robertvorthman** [comment]
It seems msg.reset has no effect if multiSensor state is "deactivating", reset only affects "active" state.  Could you please update to allow resetting while deactivating?

BTW, I love this node, it is the basis for my Home Assistant automations.  I have dozens of motion sensors and lights all governed by your multiSensor.

**Comment by TLacke** [comment]
Oh, i'll gonna check it out.
I'll created a new issue around this issue so you know.

**Comment by TLacke** [comment]
> It seems msg.reset has no effect if multiSensor state is "deactivating", reset only affects "active" state. Could you please update to allow resetting while deactivating?
> 
> BTW, I love this node, it is the basis for my Home Assistant automations. I have dozens of motion sensors and lights all governed by your multiSensor.

Sorry takin time, but issue should be fixed now.
