### ISSUE TITLE
msg.reset has no effect in state "deactivating"

### ISSUE THREAD

**Issue by TLacke** [TLacke/node-red-multi-sensor#5]
It seems msg.reset has no effect if multiSensor state is "deactivating", reset only affects "active" state.  Could you please update to allow resetting while deactivating?

BTW, I love this node, it is the basis for my Home Assistant automations.  I have dozens of motion sensors and lights all governed by your multiSensor.

_Originally posted by @robertvorthman in https://github.com/TLacke/node-red-contrib-multi-sensor/issues/2#issuecomment-937015736_

**Comment by TLacke** [comment]
Sorry taking so much time.
However, now it should work better.

Cheers

**Comment by robertvorthman** [comment]
Thank you!

**Comment by robertvorthman** [comment]
@TLacke Nodered.org still shows v1.1.3.  If it's not too much trouble it'd be great if you could publish v1.1.6 to so we can update multiSensor from the node-red palette manager.  Thanks.
