### ISSUE TITLE
Inactive output missing

### ISSUE THREAD

**Issue by schasj** [TLacke/node-red-multi-sensor#6]
I believe that I have the node properly configured for separate outputs, set as true/false:

![image](https://user-images.githubusercontent.com/2879461/185766662-ccb284a1-f33a-4f0c-81a4-fab44f364a8f.png)

However the inactive channel is not sending the false:

![image](https://user-images.githubusercontent.com/2879461/185766698-95417fcc-3266-4084-8253-70a9fa6304fc.png)

Have I missed something?

**Comment by TLacke** [comment]
It looks correct.
You should receive a "true" message directly when node receives "true"
(activation) and a "false" message, 30 seconds after node received a
"false".

According to the logs it feels like it's a problem with the custom message
with a deactivation timeout.
I'll need to setup the scenario and check it out.

Thanks for letting me know. I'll look into it.

**Comment by schasj** [comment]
Another user is using your node without issue but he temporarily used the config that I do and he confirms the issue I reported.

**Comment by schasj** [comment]
I enabled debug logging in your code and the output is below. I'm not sure that your node caused the error in the first line but I figure it's better to include it than not.

30 Aug 15:12:59 - [error] [function:multiple metrics + update available] TypeError: Cannot read properties of undefined (reading 'state')
Try activate sensor zigbee2mqtt/Upstairs Motion 2
Sensor activated.
Try activate...
Try cancel deactivation
Activating...
Activated
Getting data: true (type= bool )
sending seperated message for: { id: 1, name: 'active' } with message isActive
Updating status
Resetting sensor timeout 0
Resetting sensor timeout 0
Updating status
Try activate sensor zigbee2mqtt/Upstairs Motion 1
Sensor activated.
Try activate...
Try cancel deactivation
Resetting sensor timeout 0
Updating status
Try deactivate sensor zigbee2mqtt/Upstairs Motion 1
Sensor deactivated.
Resetting sensor timeout 0
Try deactivate...
Updating status
Try deactivate sensor zigbee2mqtt/Upstairs Motion 2
Sensor deactivated.
Resetting sensor timeout 0
Try deactivate...
Try cancel activation
Deactivate...
Timeout to deactivate 30000
sending seperated message for: { id: 3, name: 'deactivating' } no message notActive
Updating status
Updating status
Deactivated
Getting data: false (type= bool )
sending seperated message for: { id: 0, name: 'inactive' } no message notActive
Updating status

**Comment by TLacke** [comment]
Sorry taking time. Have a lot to do right now.
But I'm looking into it now and found that there's a problem in Node-Red with sending a false boolean. So the code is correct but there's a bug in node.
I'll research a little bit on this to see if there's a workaround (it should be). Otherwise, I'll need to change the implementation to return either an object or a string = 'true'/'false'.

**Comment by schasj** [comment]
I looked for the bug because it likely has wider affects than just your node but I didn't find it. I did find old bug reports that have been fixed but nothing current. Please provide the link to the bug you cite.

**Comment by TLacke** [comment]
I've found a bug in the Node-red's runtime library _(created an issue for it: https://github.com/node-red/node-red/issues/3876)_
I will however push a breaking change to ensure that the node works as default components and sends the `{payload:[value]}` instead of just **`[value]`**.

**Comment by schasj** [comment]
Good work, @TLacke :clap:

**Comment by schasj** [comment]
@TLacke, I'm not seeing it yet. Should I be?

**Comment by TLacke** [comment]
Sorry, missed the push of git. However npm should already been updated as it's independent of git. Node-red should also have been updated. _However now git is also pushed._

**Comment by schasj** [comment]
Not showing in NR Pallet Manager yet.

**Comment by schasj** [comment]
@TLacke, I'm sorry to be a pest but I'm still not seeing the update available in the NR Pallet Manager and I wonder if you forgot a step to publish it

![image](https://user-images.githubusercontent.com/2879461/189494430-9ac27a0f-a7de-4c40-948f-68a141cdf669.png)

**Comment by schasj** [comment]
Got it and it's working as expected. :+1:

**Comment by Graefer** [comment]
Same problem here, that I cannot find the update via NR palette. What can I do?

**Comment by TLacke** [comment]
What version are you running currently?
The latest version is node-red-contrib-multi-sensor@2.0.3
I've just tries it.

**Comment by schasj** [comment]
I know you're not asking me but I've been using 2.0.3 since 9/11/22 and it's working as expected. Thanks again, @TLacke!

**Comment by Graefer** [comment]
Got it. Did not know I can simply use npm to install the latest version.
