### ISSUE TITLE
JSONata

### ISSUE THREAD

**Issue by Eitraz** [TLacke/node-red-multi-sensor#7]
Hi!

After upgrading to latest version, JSONata values are put in payload object instead of message.
Previous I could set  for example "Send on active" values to
`{
   "topic": "my_topic",
   "payload": false
}`
That would result in msg.topic being "my_topic" and payload true, but after update the msg.payload is the full JSON object (topic and payload) instead.

Regards,
Petter

**Comment by TLacke** [comment]
There's a flaw in NodeRed to send object's as raw data.
It's possible to send more or less everything except 'false', that would
create a match against 'undefined'.

So I've raised the version to point an API breaking chain.
But I've might have missed something with the object emittor. Cause that
one would be able to be sent directly. But I need to check it out.

If I understand correctly, you sending in an object {name:"myobject"} and
it's being converted to {payload: {name:"myobject"}}

Is that correct?

**Comment by Eitraz** [comment]
No :)

In for example the "Send on active" field, I set the value to type JSONata with the value:
```
{
    "topic": "my_topic",
    "payload": true
}
```
What I expected (and what is was before updating) is a message with the `msg.topic = "my_topic"` and `msg.payload = true`, but instead it is a message without topic and with `msg.payload = { "topic": "my_topic", "payload": true }`

Regards,
Petter
